### ISSUE TITLE
Emojis in chat (gamifed)

### ISSUE THREAD

**Issue by sebrock** [tnyim/jungletv#11]
As a user who spent more that a defined number of BAN to queue videos I want to be rewarded with emojis, so I can show off my contributions,

**Comment by sebrock** [comment]
Found a microservice for gamification.
Requires mongoDB.

https://github.com/hpi-schul-cloud/gamification

**Comment by gbl08ma** [comment]
Implementation of custom chat emojis is blocked on
- Major rewrite of chat system, including the text input in the frontend, in order to allow for non-unicode emojis to be composed in the message
- Banano NFTs becoming viable

**Comment by gbl08ma** [comment]
We gave up on the NFT idea, at least for now (it'd be quite hard to implement and also quite hard for users to understand). Once Banano NFTs are fully implemented and there is sufficiently good tooling around them, and sufficient user awareness of how to use them, we might revisit the idea.

The final implementation is actually a bit "gamified" in the sense that most emotes are gated behind the Nice membership, which requires points, which can be obtained by enqueuing and chatting.
