### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by gbl08ma** [tnyim/jungletv#2]

**Comment by sebrock** [comment]
Ideas: 

```
:root {

  filter: invert(100%);

}
```

```
.dark-mode {

  filter: invert(100%);
 
}

```

```
let button = document.querySelector('.btn');

button.addEventListener('click', ()=>{
 
   // press the button to toggle the .dark-mode class

  document.documentElement.classList.toggle('dark-mode')

  
});
```

**Comment by gbl08ma** [comment]
I suspect the filter might combine poorly with other CSS filters already being used on the page (namely, to achieve a gradient effect when queue entry title/channel names overflow vertically).

Tailwind includes dark mode facilities that allow finer control over the result, at the expense of requiring more work: https://tailwindcss.com/docs/dark-mode

**Comment by gbl08ma** [comment]
If applied to the root node (with `:root` or `html`) that solution also has the problem of inverting the colors for the YouTube player. The only way to avoid this is to apply an additional `invert(100%)` filter on the player. But I am unsure of the performance implications this may have, especially on slower devices/browsers without graphical hardware acceleration.

**Comment by gbl08ma** [comment]
I'll leave this issue open for a bit longer to see if any major issues are identified and, once none are left, to track the addition of a more discoverable way to enable/disable the dark mode.

**Comment by gbl08ma** [comment]
I fixed a minor issue and added a nice toggle to the top bar in 72a3373490c1752480a3eeadd32b75f2ef0e0b5c. This should conclude the implementation of dark mode for now.

**Comment by sebrock** [comment]
KUDOS.
Love the dark mode!
