### ISSUE TITLE
Hover callout for address info

### ISSUE THREAD

**Issue by gbl08ma** [tnyim/jungletv#29]
Hovering over people's addresses in chat and queue could bring up an informational callout.

The callout could include:
 - Complete banano address
 - A QR code for the address (e.g. for easy tipping)
 - The monKey in a larger size (remember to use the SVG version for this)
 - (depending on how tricky the mouse/touch handling might be) explicit options to copy address and to reply to the hovered message

Once the system is sufficiently complete, this callout could also act as a kind of user profile preview, displaying some stats like the number of videos enqueued, chat messages sent, account age, etc.

Alternatively, instead of appearing on hover (might be tricky to manage on touchscreens), we could just increase the size of the "replying to message" component to include this info.

**Comment by sebrock** [comment]
Should also show the chosen nickname

**Comment by sebrock** [comment]
Love the implementation!
