### ISSUE TITLE
B-b-b-b-b-bonbibreaker!!

### ISSUE THREAD

**Issue by sebrock** [tnyim/jungletv#30]
As a mod I want to have a one-click solution which will I instantly skip a bonbi-video, play a default "B-b-b-b-b-bonbibreaker!!" video (yet to be created), and add the skipped video to the blocked videos mentioned in #27 so that skeaked in bonbi-fart videos can be dealt with quickly.

**Comment by gbl08ma** [comment]
I believe this is already covered by 9c6770180980802562b8aecc51baf15f30c574a4 which gives moderators a link to simultaneously remove a video from the queue and disallow it from being enqueued again, with a single click. The special video part seems frankly unnecessary.
