### ISSUE TITLE
Emoji support (Alternative for #11)

### ISSUE THREAD

**Issue by sebrock** [tnyim/jungletv#48]
As a jungleTV viewer i want to use Emojis in chat in order to express myself in a convenient way without having to copy/paste Emojis from somewhere else.

Recommended approach:
Implement an Emoji Chooser next to the chat input field, where I can choose Emojis from.

**Comment by gbl08ma** [comment]
This is relatively low-priority for now, as most recent operating systems offer methods to input emoji in any text input. However, it will eventually be needed anyway, as the (currently secret/being brainstormed) planned future for chat emotes on JungleTV will require a picker for them.
