### ISSUE TITLE
Kalium link on mobile doesn't always have correct data

### ISSUE THREAD

**Issue by chiajlingvoj** [tnyim/jungletv#51]
Using Firefox on Android

The quick link from the enqueuing page sometimes fills in an incorrect amount for the payment... example: the base enqueue price could be 18.5 BAN and the link will pop up in Kalium with an amount of 38 BAN. This is with no special options selected such as queue jumping or skipping or unskippable.

Thanks for all you do!

**Comment by chiajlingvoj** [comment]
I had cancelled an enqueue before when I saw that the enqueue price was too high at that time... perhaps that was the cause?

**Comment by gbl08ma** [comment]
I had tested that before, and just tested it again, and I still can't make it happen. I also went through the code and I can't see why it would happen. I wonder if it might be a Kalium bug, but I can't seem to trigger it either.

**Comment by chiajlingvoj** [comment]
No problem, it might have just been a temporary glitch... if it happens again and/or I find a way to reproduce it, I will update

**Comment by gbl08ma** [comment]
Judging by https://github.com/BananoCoin/kalium_wallet_flutter/commit/554428d238a5bad3b55a55f8169f448bcbfdfe45 this may really be/have been a problem on the Kalium side of things. However, that commit only mentions QR code scanning, not link handling. I'll leave this open so I don't forget about this.

**Comment by gbl08ma** [comment]
By now I'm pretty much certain the problem was on the Kalium side of things. Closing this.
