### ISSUE TITLE
Error 526  Invalid SSL certificate

### ISSUE THREAD

**Issue by sebrock** [tnyim/jungletv#55]
![image](https://user-images.githubusercontent.com/156824/134434885-7d772116-190e-4ca6-bdc8-b8decb9f44d4.png)

**Comment by gbl08ma** [comment]
It's fixed. Due to how the server works, the certificate only reloads when it restarts, and I'm yet to convince certbot to place the certs in a place and with permissions that the non-privileged user the server runs as can access.
