### ISSUE TITLE
Queue history

### ISSUE THREAD

**Issue by sebrock** [tnyim/jungletv#63]
As a viewer I would like to be able to see a queue history of the past 24 hours so that I can lookup what that video was which I saw last night and had forgotten to take note of.

**Comment by gbl08ma** [comment]
If you saw the video, you should be able to get it from the reward history.

A complete video history is still being thought out as it comes with moderation implications.

**Comment by sebrock** [comment]
> If you saw the video, you should be able to get it from the reward history.

Ahh right. I had not yet filly digested that this is here already. 🤦🏼‍♂️
