### ISSUE TITLE
Issue POAPs for Tunesdays contributors

### ISSUE THREAD

**Issue by sebrock** [tnyim/jungletv#64]
As a contributor eligible for the reward on a given Tunesday I would like to receive a [POAP](https://poap.xyz/) so I can build my JTV successes into my POAP collection in order to document superior bragging rights.

Contact for getting help how to implement POAPs is @oops on the Banano discord.

**Comment by gbl08ma** [comment]
POAPs are implemented on the Ethereum blockchain, which we do not endorse. The send from the [JungleTV prize distribution account](https://yellowspyglass.com/account/ban_1jtprixunfus5mozkzj5gtfm79b54p3pwnje8snh9ugu998cfk13qceepwn5) to the eligible participant's account serves as a sufficient unforgeable proof of eligible participation in the JungleTV events.
