### ISSUE TITLE
Issue POAPs for Tunesdays participants

### ISSUE THREAD

**Issue by sebrock** [tnyim/jungletv#65]
Similarily to #64 [POAP](https://poap.xyz/)s could be issued to JTV viewers present during a defined timeframe on a Tunesday.
As an anti-idler / anti-bot measure they would have to identify as humans by completing a kind of CAPTCHA challenge which works through chat.

**Comment by gbl08ma** [comment]
POAPs are implemented on the Ethereum blockchain, which we do not endorse.
